DROP TABLE IF EXISTS pub_emple;
DROP TABLE IF EXISTS existencias;
DROP TABLE IF EXISTS titular;
DROP TABLE IF EXISTS pub;
DROP TABLE IF EXISTS localidad;
DROP TABLE IF EXISTS empleado;

CREATE TABLE IF NOT EXISTS EMPLEADO (
    DNI_EMPLEADO VARCHAR(10) primary KEY,
    NOMBRE VARCHAR(20) NOT NULL,   
    DOMICILIO VARCHAR(20)
);



CREATE TABLE IF NOT EXISTS LOCALIDAD (
    COD_LOCALIDAD INT ,
    NOMBRE VARCHAR(20) NOT null,
    constraint cod_loca_pk primary key (cod_localidad)
);

CREATE TABLE IF NOT EXISTS PUB (
    COD_PUB VARCHAR(10)  PRIMARY KEY,
    NOMBRE VARCHAR(20) NOT NULL,
    LICENCIA_FISCAL VARCHAR(10) NOT NULL,
    DOMICILIO VARCHAR(20),
    FECHA_APERTURA DATE NOT NULL,
    HORARIO VARCHAR(10) check (horario = ('HOR1' or 'HOR2' or 'HOR3')),
    COD_LOCALIDAD INT not null,
    foreign key (COD_LOCALIDAD) references LOCALIDAD (COD_LOCALIDAD) on delete CASCADE
);

CREATE TABLE IF NOT EXISTS TITULAR (
    DNI_TITULAR VARCHAR(10) primary KEY,
    NOMBRE VARCHAR(20)NOT NULL,  
    DOMICILIO VARCHAR(20) NOT NULL,
    COD_PUB VARCHAR(10) NOT NULL,
    FOREIGN KEY (COD_PUB) REFERENCES PUB(COD_PUB) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS EXISTENCIAS (
    COD_ARTICULO VARCHAR(10) PRIMARY KEY,
    NOMBRE VARCHAR(20)NOT NULL,  
    CANTIDAD INT NOT NULL,
    PRECIO INT NOT null,
    COD_PUB VARCHAR(10) NOT NULL,
    CHECK(PRECIO>0),
    FOREIGN KEY (COD_PUB) REFERENCES PUB(COD_PUB) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS PUB_EMPLE (
    FUNCION ENUM ('CAMARERO', 'SEGURIDAD', 'LIMPIEZA') NOT NULL,
    COD_PUB VARCHAR(10),
    DNI_EMPLEADO VARCHAR(10),
    PRIMARY KEY (COD_PUB,DNI_EMPLEADO),
    FOREIGN KEY (COD_PUB) REFERENCES PUB(COD_PUB),
    FOREIGN KEY (DNI_EMPLEADO) REFERENCES EMPLEADO(DNI_EMPLEADO)
);